import { useEffect, useRef } from "react";

import { App } from "@capacitor/app";
import { Capacitor } from "@capacitor/core";

import { useSubscriptionStore } from "@/features/finance/store/subscriptionStore";
import { useTransactionStore } from "@/features/finance/store/transactionStore";
import { generateDueTransactions } from "@/features/finance/services/subscriptionTransactionService";
import { useToastStore } from "@/store/toastStore";
import { translate } from "@/i18n/useTranslation";

// Foreground-only due-subscription check, mounted once in MainLayout
// alongside ScanRecoveryNotice/PendingPaymentSheet -- runs on mount and on
// every native app resume (mirrors usePendingNotificationCandidates.ts's
// exact pattern). Unlike that hook, the check itself is pure Dexie/store
// logic with no native dependency, so only the resume *listener* is
// native-gated -- a web session still gets the check once per app mount.
export default function SubscriptionDueCheck() {
  const runningRef = useRef(false);

  useEffect(() => {
    async function run() {
      if (runningRef.current) return;
      runningRef.current = true;

      try {
        const { subscriptions, loadSubscriptions, updateSubscription } = useSubscriptionStore.getState();
        if (subscriptions.length === 0) await loadSubscriptions();

        const { addTransaction } = useTransactionStore.getState();
        const { transactionCount, subscriptionCount } = await generateDueTransactions(
          useSubscriptionStore.getState().subscriptions,
          addTransaction,
          updateSubscription
        );

        if (transactionCount > 0) {
          useToastStore
            .getState()
            .show("info", translate("subscriptions.autoGeneratedToast", { count: transactionCount, subscriptionCount }));
        }
      } finally {
        runningRef.current = false;
      }
    }

    void run();

    if (!Capacitor.isNativePlatform()) return;

    const listenerPromise = App.addListener("resume", () => {
      void run();
    });

    return () => {
      void listenerPromise.then((handle) => handle.remove());
    };
  }, []);

  return null;
}
