// Server-generated by public.generate_weekly_digests() (supabase/schema.sql),
// scheduled via pg_cron -- never written by the client. See
// docs/DECISIONS.md for why this only ever exists for non-encrypted
// accounts (the server literally cannot read an encrypted user's
// transaction data).
export interface WeeklyDigest {
  id: string;
  period_start: string;
  period_end: string;
  income: number;
  expense: number;
  net: number;
  transaction_count: number;
}
