import { advanceOneBillingCycle } from "@/features/finance/utils/subscriptionMath";
import { toLocalDateString } from "@/utils/localDate";
import { translate } from "@/i18n/useTranslation";
import type { Subscription, Transaction } from "@/features/finance/types";

// Safety bound on how many missed cycles a single stale subscription can
// catch up on in one pass -- covers a year of monthly bills. Prevents a
// pathological loop from a very old nextBillingDate, while still honestly
// generating one transaction per real billing cycle rather than merging or
// silently dropping them.
const MAX_CATCHUP_CYCLES = 12;

export interface GenerateDueTransactionsResult {
  transactionCount: number;
  subscriptionCount: number;
}

// Foreground-only due-subscription check (this app has no background/cron
// mechanism anywhere). Reuses nextBillingDate itself as the idempotency
// signal -- no separate "last generated" marker field -- by advancing and
// persisting it immediately after each transaction it creates, before
// moving to the next cycle. Deliberately leaves `recurring` unset on the
// generated transaction so it isn't double-counted by the pre-existing
// useSubscriptions.ts detector, which filters on `recurring` being set.
export async function generateDueTransactions(
  subscriptions: Subscription[],
  addTransaction: (transaction: Transaction) => Promise<void>,
  updateSubscription: (id: number, subscription: Subscription) => Promise<void>,
  asOf: Date = new Date()
): Promise<GenerateDueTransactionsResult> {
  const today = toLocalDateString(asOf);
  let transactionCount = 0;
  let subscriptionCount = 0;

  for (const subscription of subscriptions) {
    // A transaction requires an account; a subscription with none set is
    // not eligible for auto-generation (inventing a default account is out
    // of scope). Paused/cancelled subscriptions never generate.
    if (subscription.status !== "active" || !subscription.account || subscription.id === undefined) continue;

    let nextBillingDate = subscription.nextBillingDate;
    let generatedForThisSubscription = 0;

    while (nextBillingDate <= today && generatedForThisSubscription < MAX_CATCHUP_CYCLES) {
      await addTransaction({
        title: subscription.name,
        amount: subscription.amount,
        type: "expense",
        account: subscription.account,
        category: subscription.category,
        date: nextBillingDate,
        note: translate("subscriptions.autoGeneratedNote"),
      });

      nextBillingDate = advanceOneBillingCycle(nextBillingDate, subscription.billingFrequency);
      await updateSubscription(subscription.id, { ...subscription, nextBillingDate });

      transactionCount++;
      generatedForThisSubscription++;
    }

    if (generatedForThisSubscription > 0) subscriptionCount++;
  }

  return { transactionCount, subscriptionCount };
}
