import { advanceOneBillingCycle, resolveBillingAnchorDay } from "@/features/finance/utils/subscriptionMath";
import { toLocalDateString } from "@/utils/localDate";
import { translate } from "@/i18n/useTranslation";
import type { Subscription, Transaction } from "@/features/finance/types";

// Safety bound on how many missed cycles a single stale subscription can
// catch up on in one pass -- covers a year of monthly bills. Prevents a
// pathological loop from a very old nextBillingDate, while still honestly
// generating one transaction per real billing cycle rather than merging or
// silently dropping them.
const MAX_CATCHUP_CYCLES = 12;

export interface GenerateDueTransactionsResult {
  transactionCount: number;
  subscriptionCount: number;
}

// Foreground-only due-subscription check (this app has no background/cron
// mechanism anywhere). Reuses nextBillingDate itself as the idempotency
// signal -- no separate "last generated" marker field -- by advancing and
// persisting it *before* creating the cycle's transaction, not after (see
// below). Deliberately leaves `recurring` unset on the generated
// transaction so it isn't double-counted by the pre-existing
// useSubscriptions.ts detector, which filters on `recurring` being set.
export async function generateDueTransactions(
  subscriptions: Subscription[],
  addTransaction: (transaction: Transaction) => Promise<void>,
  updateSubscription: (id: number, subscription: Subscription) => Promise<void>,
  asOf: Date = new Date()
): Promise<GenerateDueTransactionsResult> {
  const today = toLocalDateString(asOf);
  let transactionCount = 0;
  let subscriptionCount = 0;

  for (const subscription of subscriptions) {
    // A transaction requires an account; a subscription with none set is
    // not eligible for auto-generation (inventing a default account is out
    // of scope). Paused/cancelled subscriptions never generate.
    if (subscription.status !== "active" || !subscription.account || subscription.id === undefined) continue;

    let nextBillingDate = subscription.nextBillingDate;
    let generatedForThisSubscription = 0;
    // Resolved once per subscription, from its ORIGINAL (pre-loop) date and
    // stored anchor -- must stay fixed across every catch-up cycle below
    // (BUG-12): re-deriving it from an already-clamped nextBillingDate on a
    // later iteration would silently rebase the anchor down to whatever day
    // that clamp landed on. Persisting it below also backfills it, for
    // free, onto any subscription created before this field existed.
    const anchorDay = resolveBillingAnchorDay(subscription.nextBillingDate, subscription.billingAnchorDay);

    while (nextBillingDate <= today && generatedForThisSubscription < MAX_CATCHUP_CYCLES) {
      const dueDate = nextBillingDate;
      nextBillingDate = advanceOneBillingCycle(nextBillingDate, subscription.billingFrequency, anchorDay);

      // Persisted *before* the transaction is created, not after: this pair
      // isn't atomic (updateSubscription's own reminder cancel/reschedule
      // includes a native plugin call that can fail independently of the
      // DB write), and a failure between the two must never leave a
      // transaction created with nextBillingDate still stuck on the same
      // due cycle -- that would recreate the same transaction again on
      // every future run, forever. Advancing first means the worst case of
      // a failure here is a missed transaction for this cycle, not a
      // duplicated one.
      await updateSubscription(subscription.id, { ...subscription, nextBillingDate, billingAnchorDay: anchorDay });

      await addTransaction({
        title: subscription.name,
        amount: subscription.amount,
        type: "expense",
        account: subscription.account,
        category: subscription.category,
        date: dueDate,
        note: translate("subscriptions.autoGeneratedNote"),
      });

      transactionCount++;
      generatedForThisSubscription++;
    }

    if (generatedForThisSubscription > 0) subscriptionCount++;
  }

  return { transactionCount, subscriptionCount };
}
